import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class MyIcons {
  static const IconData document = Icons.text_snippet_outlined;
  static const IconData image = Icons.image_outlined;
  static const IconData pdf = Icons.picture_as_pdf_outlined;
  static const IconData video = Icons.video_file_outlined;
  static const IconData audio = Icons.audio_file_outlined;
  static const IconData arrowDown = Icons.keyboard_arrow_down_rounded;
  static const IconData menu = Icons.menu;
  static const IconData add = Icons.add;
  static const IconData noImage = Icons.image_not_supported_outlined;
  static const IconData contact = Icons.contact_page;
  static const IconData arrowRight = Icons.keyboard_arrow_right;
  static const IconData addDocument = Icons.note_add_rounded;
  static const IconData help = Icons.info;
  static const IconData logout = Icons.logout_rounded;
  static const IconData login = Icons.login;
  static const IconData lock = Icons.lock_outlined;
  static const IconData eye = Icons.visibility;
  static const IconData eyeOff = Icons.visibility_off;
  static const IconData calendar = Icons.calendar_month_outlined;
  static const IconData money = CupertinoIcons.money_dollar_circle;
  static const IconData attachFile = Icons.file_present_outlined;
  static const IconData download = Icons.file_download_outlined;
  static const IconData arrowUp = Icons.keyboard_arrow_up_rounded;
  static const IconData send = CupertinoIcons.paperplane_fill;
  static const IconData minus = Icons.remove;
  static const IconData lockClock = Icons.lock_clock_outlined;
  static const IconData error = Icons.error_outline_outlined;
  static const IconData check = Icons.check_circle_outline_outlined;
  static const IconData upload = Icons.file_upload_outlined;
  static const IconData close = Icons.close;
  static const IconData person = Icons.person;
  static const IconData save = Icons.save;
  static const IconData checkFill = Icons.check_circle;
  static const IconData closeFill = CupertinoIcons.clear_thick_circled;
  static const IconData chamthanFill = CupertinoIcons.exclamationmark_circle_fill;
  static const IconData questionMark = Icons.question_mark;
  static const IconData notification = Icons.notifications_none;
  static const IconData more = Icons.more_vert;
  static const IconData delete = Icons.delete_outline_rounded;
  static const IconData remove = Icons.remove_circle_rounded;
}